feat: opt-in for access logs
entur/terraform-google-cloud-storage pull request #17
Opened 2023-10-11 12:03 UTC by alovh

2023-10-11 12:26 UTC, AlexanderBrevig requested changes

2023-10-11 12:29 UTC, AlexanderBrevig commented on modules/bucket/main.tf
> +  log_bucket_name  = var.enable_access_logs ? "ent-gcs-${local.bucket_shortname}-${var.init.environment}-${local.generation}-access-logs" : ""
https://enturas.atlassian.net/wiki/spaces/ESP/pages/3182264469/Naming+conventions+on+GCP

2023-10-11 13:07 UTC, alovh commented on examples/minimal_test/main.tf
> +  enable_access_logs = var.enable_access_logs != null ? var.enable_access_logs : true
haha, her har jeg tenkt litt for hardt ja XD

2023-10-11 13:17 UTC, alovh commented on modules/bucket/main.tf
> +  log_bucket_name  = var.enable_access_logs ? "ent-gcs-${local.bucket_shortname}-${var.init.environment}-${local.generation}-access-logs" : ""
made it a vote :)

2023-10-12 09:08 UTC, AlexanderBrevig requested changes
Did we figure out if there exists a default log bucket? Should we use that if that's the case?

2023-10-12 09:08 UTC, AlexanderBrevig commented on modules/bucket/variables.tf
> +  description = "Set to true to enable access logs, log bucket will have bucket shortname appended with 'access-logs'. Bucket 'ent-gcs-foo-dev-001' will have access logs in bucket 'ent-gcs-foo-access
doc does not match the test case `"ent-gcs-%s-axlogs-dev-%s"`

2023-10-12 09:36 UTC, alovh commented
> Did we figure out if there exists a default log bucket? Should we use that if that's the case?

funny thing, there is, but we cannot actively send logs to the log buckets, they must be sent to a storage bucket. And a default log storage bucket does not exist. added a comment in the issue btw

2023-10-12 09:59 UTC, AlexanderBrevig commented on modules/bucket/variables.tf
> +  description = "Set to true to enable access logs, log bucket will have bucket shortname appended with 'access-logs'. Bucket 'ent-gcs-foo-dev-001' will have access logs in bucket 'ent-gcs-foo-access
maybe a simple `logs` infix is better? Shorter than `access-logs` and easier to understand than `axlogs`?

2023-11-03 15:15 UTC, AlexanderBrevig commented on modules/bucket/variables.tf
> +  description = "Set to true to enable access logs, log bucket will have bucket shortname appended with 'access-logs'. Bucket 'ent-gcs-foo-dev-001' will have access logs in bucket 'ent-gcs-foo-access
There's a mismatch between what's documented and what actually happens.
What do you think about the suggestion of using only a simple `logs` infix?

2024-04-04 12:21 UTC, closed without merging