test: add tests
entur/terraform-google-cloud-storage pull request #5
Opened 2022-11-21 15:17 UTC by bvestli

This will add unit and integration tests using terratest and GitHub workflows to run the automatically

2022-11-23 12:34 UTC, tommybo-entur commented
Jeg tenker at følgende (defaults) bør verifiseres under test:

- force destroy er false
- storage purpose er standard
- label for disable_offsite_backup ikke er satt
- objektversjonering er aktivert
- retention på utdaterte objekter er 2 dager
- config map opprettes

2022-11-28 09:20 UTC, bvestli commented
Unit test updated. Ready for review.

2022-11-28 13:55 UTC, tommybo-entur commented
Bør kanskje skrive en setning om hvordan man kjører enhetstesten lokalt?

2022-11-28 13:58 UTC, tommybo-entur requested changes

2022-11-28 13:58 UTC, tommybo-entur commented on tests/cloud_storage_unit_test.go
> +	assert.Emptyf(t, disable_offsite_backup, "Fount label disable_offsite_backup. This should only exist when set in a production environment.")
Fount > Found

2022-11-28 14:00 UTC, tommybo-entur commented on tests/cloud_storage_unit_test.go
> +	assert.Emptyf(t, disable_offsite_backup, "Fount label disable_offsite_backup. This should only exist when set in a production environment.")
Kommentaren om hvordan man kjører enhetstesten lokalt er også en del av request for change ;-)

2022-11-29 07:42 UTC, tommybo-entur commented on .github/workflows/pr-int-test-terraform.yml
> +  push:
Denne gjør at testen ikke blir kjørt ved endringer kun i testen.

2022-11-29 08:56 UTC, tommybo-entur approved these changes
Very good.
A couple of comments, though (for reflection):
I do not see the gain of limiting when to run the build. It introduce corner cases of pushing code that may change behavior without running the tests.
I do prefer testing requirements separately, that is asserting one requirement per test. For regressions it's delightful when the test pinpoint broken requirement and additionally by having all asserts in one test you risk hiding errors as the test ends on first failure.

2022-11-29 12:28 UTC, merged