feat!: Make creation of Kubernetes resources togglable
entur/terraform-google-cloud-storage pull request #8
Opened 2023-08-10 16:41 UTC by sindrel

The storage module currently requires a Kubernetes cluster to provision a bucket, which shouldn't be a requirement.

* This PR adds the ability to opt out of Kubernetes resource creation.
* Still defaults to provisioning a Kubernetes config map.

⚠️ **Breaking change**
Note that this will likely introduce re-creation of the config map, as the Terraform resource address will change (adding an index). The use of a moved-block is not implemented, as we still maintain backwards compatibility with >=0.13.2.

2023-08-10 19:01 UTC, AlexanderBrevig requested changes
This is not breaking, as in call-site needs changing. API stays the same, the content of the ConfigMap stays the same and the app will not be affected. I think this is a `feat` not a `feat!`.

https://github.com/entur/terraform-google-sql-db/commit/2c0499dbb1d4e100ed6b298d8d1b26a0ab98adc7 was a `feat` and we had no issues rolling it out.

2023-08-11 07:42 UTC, sindrel commented
> This is not breaking, as in call-site needs changing. API stays the same, the content of the ConfigMap stays the same and the app will not be affected. I think this is a `feat` not a `feat!`.
> 
> [entur/terraform-google-sql-db@2c0499d](https://github.com/entur/terraform-google-sql-db/commit/2c0499dbb1d4e100ed6b298d8d1b26a0ab98adc7) was a `feat` and we had no issues rolling it out.

I agree - I'll mark it down. I chose to be on the cautious side in case this could cause service disruption in some way. But given some afterthought, this should be unproblematic apart from it triggering execution of Terraform Apply workflows.

I'll leave a note in the PR so that consumers are aware of the change and what it means.

2023-08-11 07:53 UTC, sindrel commented
PR description updated.

2023-08-11 08:22 UTC, AlexanderBrevig approved these changes

2023-08-11 10:00 UTC, merged